#ifndef INCLUDES_H
#define INCLUDES_H
#include <Chain/NAIAChain.h>
#include <NSL/AllSelections.h>
#include <iostream>
#include <fstream>
#include <filesystem>
#include <TFile.h>
#include <TF1.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TGraphErrors.h>
#include <TStyle.h>
#include <TChain.h>
#include <TMath.h>
#include <TTree.h>
#include <TString.h>
#include <TCanvas.h>
#include <Math/Minimizer.h>
#include <TVirtualFitter.h>
#include <TEfficiency.h>
#include "TString.h"
#include "TTimeStamp.h"
#include "TKey.h"
#include <TROOT.h>
#include <TSystem.h>
#include <string>
#include <vector>

#include "Efficiencies/Tracker.h"
#include "Efficiencies/Trigger.h"
#include "Efficiencies/InnerTracker.h"
#include "Efficiencies/TofStandalone.h"
#include "Efficiencies/RTI.h"
#include "Efficiencies/MySel.h"
#include "Efficiencies/TRD.h"
#endif
